"""Interpreter hooks shared by legacy demos and private live workflows."""

from typing import Protocol


class RuntimeHooks(Protocol):
    is_demo: bool

    def compatible(self, program, environment) -> bool: ...
    async def observe(self, session) -> dict: ...
    async def verify(self, session, program, before, after, inputs) -> list: ...
    async def before_step(self, session, step, inputs) -> None: ...
    async def after_step(self, session, step, inputs) -> None: ...
    async def resume(self, session, url) -> None: ...
    def effect_status(self) -> str: ...
    def lift(self, trace, network) -> list: ...
